// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaPlace.DB;

#nullable disable

namespace PizzaPlace.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PizzaPlace.Models.PizzaRecipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CookingTimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("RecipeType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PizzaRecipes");
                });

            modelBuilder.Entity("PizzaPlace.Models.Stock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<long>("PizzaRecipeId")
                        .HasColumnType("bigint");

                    b.Property<int>("StockType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PizzaRecipeId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("PizzaPlace.Models.Stock", b =>
                {
                    b.HasOne("PizzaPlace.Models.PizzaRecipe", "PizzaRecipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("PizzaRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PizzaRecipe");
                });

            modelBuilder.Entity("PizzaPlace.Models.PizzaRecipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
